name: Build packages

on:
  push: 
    branches:
      - main
  pull_request:

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Checkout vcpkg repo
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          ref: 2024.08.23
          fetch-depth: 1
          path: vcpkg
      - name: Install clang 19.x-objc
        run: |
          Remove-Item -Recurse 'C:\Program Files\LLVM\'
          Invoke-WebRequest -UseBasicParsing -Uri https://qmcdn.blob.core.windows.net/gnustep/clang-19.x-objc.zip -OutFile clang-19.x-objc.zip
          Expand-Archive -Path clang-19.x-objc.zip -DestinationPath 'C:\Program Files\LLVM\' -Force
          & 'C:\Program Files\LLVM\bin\clang.exe' --version
      - name: Check LLVM version
        # We need at least LLVM 18.0 for proper Objective C support.  Visual Studio 2022 ships with LLVM 17,
        # so we need to make sure we pick up clang from C:\Program Files\LLVM\bin\
        # For full-fledged support on Windows, we'll need https://github.com/llvm/llvm-project/pull/107604,
        # which will be included in LLVM 20.0
        run: clang --version
      - name: Bootstrap vcpkg
        run: ./vcpkg/scripts/bootstrap.ps1
      - name: Install libobjc2
        run: ./vcpkg/vcpkg.exe install libobjc2:x64-windows-llvm --overlay-ports=./ports --overlay-triplets=./triplets
      - name: Install libdispatch
        run: ./vcpkg/vcpkg.exe install libdispatch:x64-windows-llvm --overlay-ports=./ports --overlay-triplets=./triplets
      - name: Install gnustep-make
        run: ./vcpkg/vcpkg.exe install gnustep-make:x64-windows-llvm --overlay-ports=./ports --overlay-triplets=./triplets
      - name: Install gnustep-base
        run: ./vcpkg/vcpkg.exe install gnustep-base:x64-windows-llvm --overlay-ports=./ports --overlay-triplets=./triplets
      - name: Install gnustep-gui
        run: ./vcpkg/vcpkg.exe install gnustep-gui:x64-windows-llvm --overlay-ports=./ports --overlay-triplets=./triplets
      - name: Install gnustep-headless
        run: ./vcpkg/vcpkg.exe install gnustep-headless:x64-windows-llvm --overlay-ports=./ports --overlay-triplets=./triplets
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: installed-windows
          path: ./vcpkg/installed
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: buildtrees-windows
          path: ./vcpkg/buildtrees/**/*.log

  linux:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu-22.04
            image: ubuntu:22.04
            family: ubuntu
          - name: ubuntu-24.04
            image: ubuntu:24.04
            family: ubuntu
          - name: rockylinux-9
            image: rockylinux:9
            family: rhel
            # Some packages, such as giflib-devel, are not in the base RHEL repos but in an additional repository;
            # which was named 'powertools' on RHEL8 and 'CodeReady Builder' on RHEL9.
            # See https://wiki.rockylinux.org/rocky/repo/#notes-on-crb
            repos: crb
          - name: rockylinux-8
            image: rockylinux:8
            family: rhel
            repos: powertools
    steps:
      - uses: actions/checkout@v4
      - name: Checkout vcpkg repo
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          ref: 2024.08.23
          fetch-depth: 1
          path: vcpkg
      - name: Install dependencies (Ubuntu)
        run: |
          apt-get update
          apt-get install -y clang lld curl zip unzip tar git pkg-config make
        if: matrix.family == 'ubuntu'
      - name: Install dependencies (Enterprise Linux)
        run: |
          yum install -y clang lld zip unzip tar git pkg-config which
        if: matrix.family == 'rhel'
      - name: Bootstrap vcpkg
        run: ./vcpkg/bootstrap-vcpkg.sh
      - name: Install libobjc2
        run: ./vcpkg/vcpkg install libobjc2:x64-linux-llvm --overlay-ports=./ports --overlay-triplets=./triplets
      - name: Install libdispatch
        run: ./vcpkg/vcpkg install libdispatch:x64-linux-llvm --overlay-ports=./ports --overlay-triplets=./triplets
      - name: Install gnustep-make
        run: ./vcpkg/vcpkg install gnustep-make:x64-linux-llvm --overlay-ports=./ports --overlay-triplets=./triplets
      - name: Install gnustep-base dependencies (Ubuntu)
        run: |
          apt-get update
          apt-get install -y libxml2-dev libxslt-dev libcurl4-gnutls-dev gnutls-dev libffi-dev libicu-dev
        if: matrix.family == 'ubuntu'
      - name: Install gnustep-base dependencies (Enterprise Linux)
        run: |
          yum install -y libxml2-devel libxslt-devel libcurl-devel gnutls-devel libffi-devel libicu-devel
        if: matrix.family == 'rhel'
      - name: Install gnustep-base
        run: ./vcpkg/vcpkg install gnustep-base:x64-linux-llvm --overlay-ports=./ports --overlay-triplets=./triplets
      - name: Install gnustep-gui dependencies (Ubuntu)
        run: |
          apt-get update
          apt-get install -y libtiff-dev libpng-dev libjpeg-dev libgif-dev
        if: matrix.family == 'ubuntu'
      - name: Install gnustep-base dependencies (Enterprise Linux)
        run: |
          yum install --enablerepo=${{ matrix.repos}} -y libtiff-devel libpng-devel libjpeg-devel giflib-devel
        if: matrix.family == 'rhel'
      - name: Install gnustep-gui
        run: ./vcpkg/vcpkg install gnustep-gui:x64-linux-llvm --overlay-ports=./ports --overlay-triplets=./triplets
      - name: Install gnustep-headless
        run: ./vcpkg/vcpkg install gnustep-headless:x64-linux-llvm --overlay-ports=./ports --overlay-triplets=./triplets
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: installed-${{ matrix.name }}
          path: ./vcpkg/installed
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: buildtrees-${{ matrix.name }}
          path: ./vcpkg/buildtrees/**/*.log
